spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/veloz
    username: root
    password:
    platform: all
  jpa:
    show-sql: true
server:
  port: 8088

---

spring:
  profiles: test
  application:
    name: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8086



